version: '3'
services:

 full:
  image: blckchnd/peerplays-mainnet:1.0.0
  build:
    context: ./dkr
  environment:
   - 'PEERPLAYSD_SEED_NODES=seed.ppy.blckchnd.com:6112'
   - 'PEERPLAYSD_RPC_ENDPOINT=0.0.0.0:8090'
   - 'PEERPLAYSD_P2P_ENDPOINT=0.0.0.0:6666'
   - 'PEERPLAYSD_PRIVATE_KEY=["TEST...","5..."]'
   - 'PEERPLAYSD_WITNESS_ID="1.6.x"'
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
  ports:
  # - "0.0.0.0:6666:6666"
  volumes:
   - "./data:/var/lib/peerplays"
