version: '3'
services:

 seed:
  #
  # Seed Node
  # =========
  #
  # This service can be used to deploy a seed node that exposes the P2P
  # port to the internet at port 6666 (change below)
  #
  image: blckchnd/peerplays-beatrice:latest
  build:
    context: ./dkr
  environment:
   - 'PEERPLAYSD_P2P_ENDPOINT=0.0.0.0:6666'
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
  ports:
   - "0.0.0.0:6666:6666"
  volumes:
   - "./seed:/var/lib/peerplays"

 api:
  #
  # API
  # ====
  #
  # This service can be used to deploy a full node that exposes the RPC
  # port to the internet at port 8090 (change below)
  #
  image: blckchnd/peerplays-beatrice:latest
  ports:
   - "0.0.0.0:8090:8090"
  environment:
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
  volumes:
  - "./api:/var/lib/peerplays"

 witness:
  #
  # Witness Node
  # =========
  #
  # This service can be used to deploy a block producer.
  #
  # NOTE:
  # Please change the private key and witness id accordingly!!
  #
  image: blckchnd/peerplays-beatrice:latest
  environment:
#   - 'PEERPLAYSD_PRIVATE_KEY=["TEST...","51111..."]'
#   - 'PEERPLAYSD_WITNESS_ID="1.6.1"'
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
  volumes:
  - "./witness:/var/lib/peerplays"
